### ISSUE TITLE
Expectation in term of memory overhead ?

### ISSUE THREAD

**Issue by allan-simon** [michaelsproul/rust_sequence_trie#23]
when I run a  SequenceTrie<u8, ()>   made of 140k string element (that set up as a json takes 1.8MB) 

it takes ~1GB when in memory,  is that expected ? or is there something we can fix to make it more memory efficient ?

**Comment by michaelsproul** [comment]
Woaaah, that's insane! Assuming you're branching on bytes that's still ~10,000 bytes of trie per byte of string! I'll look into this a bit more in the next few days although I'm afraid it may be an inherent limitation of the design. This library was originally written for [iron/mount](https://github.com/iron/mount) which doesn't have tight memory/performance  requirements due to the expected size of the data sets. I have a lot more faith that my radix trie could be nicely optimised, so perhaps effort should be directed there.

**Comment by allan-simon** [comment]
ok, seems like i will need to implement the missing methods in radix trie ^^

**Comment by michaelsproul** [comment]
@allan-simon: I just overhauled the structure of the radix trie, I hope this hasn't impacted any work you were doing on it. I'm about to start work on iterators and prefix methods.

**Comment by allan-simon** [comment]
@michaelsproul , thanks for the notice,  fortunately yesterday i felt tired and went to bed early so i put to "tomorrow" my plan to implement the iterator with a stack as you did for sequence trie, so well seems like my dad advice "why doing today something that can be done tomorrow .... and by someone else"  has paid once again :P 

I can't wait to get the iterators and prefix methods \o
